"""pricing_plan_update

Revision ID: bc83450d702f
Revises: 124ef7961663
Create Date: 2024-12-22 12:36:52.647848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc83450d702f"
down_revision: Union[str, None] = "124ef7961663"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "features",
        "processor_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "features",
        "ram",
        existing_type=sa.NUMERIC(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "features",
        "disk_type",
        existing_type=postgresql.ENUM("HDD", "SSD", "NVME", name="disktype"),
        nullable=True,
    )
    op.alter_column(
        "features", "network_speed", existing_type=sa.NUMERIC(), nullable=True
    )
    op.alter_column(
        "features", "network_limit", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column(
        "pricing_plans",
        sa.Column(
            "additional_info",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pricing_plans", "additional_info")
    op.alter_column(
        "features", "network_limit", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "features", "network_speed", existing_type=sa.NUMERIC(), nullable=False
    )
    op.alter_column(
        "features",
        "disk_type",
        existing_type=postgresql.ENUM("HDD", "SSD", "NVME", name="disktype"),
        nullable=False,
    )
    op.alter_column(
        "features",
        "ram",
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(),
        existing_nullable=False,
    )
    op.alter_column(
        "features",
        "processor_name",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    # ### end Alembic commands ###
