"""made template_id nullable

Revision ID: 912e09ac6f83
Revises: 8af3e71e810d
Create Date: 2024-12-15 00:03:46.601617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "912e09ac6f83"
down_revision: Union[str, None] = "8af3e71e810d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "notifications", "template_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "notifications", "template_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
